clear;
clc;

basePath_1 = '/home/vahid/RL_project_1/part1/data/train_class/';
basePath_2 = '/home/vahid/RL_project_1/part2/data/train_class/';
basePath_3 = '/home/vahid/RL_project_1/part3/data/train_class/';

imgSets = [ imageSet( fullfile( basePath_1, 'tiff_class/', '1'  ) ), ...
            imageSet( fullfile( basePath_2, 'tiff_class/', '1'  ) ), ...
            imageSet( fullfile( basePath_3, 'tiff_class/', '1'  ) ), ...
            imageSet( fullfile( basePath_1, 'tiff_class/', '2'  ) ), ...
            imageSet( fullfile( basePath_2, 'tiff_class/', '2'  ) ), ...
            imageSet( fullfile( basePath_3, 'tiff_class/', '2'  ) ), ...
            imageSet( fullfile( basePath_1, 'tiff_class/', '3'  ) ), ...
            imageSet( fullfile( basePath_2, 'tiff_class/', '3'  ) ), ...
            imageSet( fullfile( basePath_3, 'tiff_class/', '3'  ) ), ...
            imageSet( fullfile( basePath_1, 'tiff_class/', '4'  ) ), ...
            imageSet( fullfile( basePath_2, 'tiff_class/', '4'  ) ), ...
            imageSet( fullfile( basePath_3, 'tiff_class/', '4'  ) ), ...
            imageSet( fullfile( basePath_1, 'tiff_class/', '5'  ) ), ...
            imageSet( fullfile( basePath_2, 'tiff_class/', '5'  ) ), ...
            imageSet( fullfile( basePath_3, 'tiff_class/', '5'  ) ), ...
            imageSet( fullfile( basePath_1, 'tiff_class/', '6'  ) ), ...
            imageSet( fullfile( basePath_2, 'tiff_class/', '6'  ) ), ...
            imageSet( fullfile( basePath_3, 'tiff_class/', '6'  ) ), ...
            imageSet( fullfile( basePath_1, 'tiff_class/', '7'  ) ), ...
            imageSet( fullfile( basePath_2, 'tiff_class/', '7'  ) ), ...
            imageSet( fullfile( basePath_3, 'tiff_class/', '7'  ) ), ...
            imageSet( fullfile( basePath_1, 'tiff_class/', '8'  ) ), ...
            imageSet( fullfile( basePath_2, 'tiff_class/', '8'  ) ), ...
            imageSet( fullfile( basePath_3, 'tiff_class/', '8'  ) ), ...
            imageSet( fullfile( basePath_1, 'tiff_class/', '9'  ) ), ...
            imageSet( fullfile( basePath_2, 'tiff_class/', '9'  ) ), ...
            imageSet( fullfile( basePath_3, 'tiff_class/', '9'  ) ), ...
            imageSet( fullfile( basePath_1, 'tiff_class/', '10' ) ), ...
            imageSet( fullfile( basePath_2, 'tiff_class/', '10' ) ), ...
            imageSet( fullfile( basePath_3, 'tiff_class/', '10' ) ), ...
            imageSet( fullfile( basePath_1, 'tiff_class/', '11' ) ), ...
            imageSet( fullfile( basePath_2, 'tiff_class/', '11' ) ), ...
            imageSet( fullfile( basePath_3, 'tiff_class/', '11' ) ), ...
            imageSet( fullfile( basePath_1, 'tiff_class/', '12' ) ), ...
            imageSet( fullfile( basePath_2, 'tiff_class/', '12' ) ), ...
            imageSet( fullfile( basePath_3, 'tiff_class/', '12' ) ), ...
          ];
      
%minSetCount = min( [imgSets.Count] );

%imgSets = partition( imgSets, minSetCount, 'randomize' );

[imgSets.Count];

[trainingSets, validationSets] = partition( imgSets, 0.98, 'randomize' );

bag = bagOfFeatures( trainingSets,'VocabularySize', 7000, 'CustomExtractor', @extractorFcn );

categoryClassifier = trainImageCategoryClassifier(trainingSets, bag);

confMatrix = evaluate(categoryClassifier, trainingSets);

confMatrix = evaluate(categoryClassifier, validationSets);

mean(diag(confMatrix))